apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app:  backend
    component: backend
    environment: development 
spec:
  template:
    spec:
      containers:
      - name: backend
        image: eultengodevacr01.azurecr.io/backend:1.2.13