apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    app:  frontend
    component: front
    environment: development  
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: eultengodevacr01.azurecr.io/frontend:1.2.9
