apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: uledwin/backend       
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds           
    argocd-image-updater.argoproj.io/git-branch: feature                                         
    #argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/uledwin/rampupk8sdeployment.git
    targetRevision: v0.3.0
    path: overlays/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default


  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true