apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app:  backend-service
    component: backend-service
    environment: development 
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000