apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    app:  frontend
    component: front
    environment: development 
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
      - name:  frontend
        image:  uledwin/frontend
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        env:
        - name: BACKEND_URL
          value: "backend-service:3000"
        - name: PORT
          value: "8080"
        ports:
        - containerPort:  8080
          name:  frontend
      restartPolicy: Always