apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: frontend-service
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001